name: Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: ValorantMenuChanger
        path: bin/release/net5.0/*.*
